import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/subcomponents/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arinjay's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
